spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgres.JDBC
    url: jdbc:postgresql://postgres.container.local.jmpd.in:5432/payments
    username: postgres
    password: password
  cloud:
    vault:
      host: localhost
      scheme: http
      port: 8200
      fail-fast: true
      authentication: APPROLE
      app-role: 
        role: spring-vault-example