spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:database.db
    username: sa
    password: sa
  cloud:
    vault:
      host: localhost
      scheme: http
      port: 8200
      fail-fast: true
      authentication: APPROLE
      app-role: 
        role: spring-vault-example