logging:
  level:
    root: INFO
    org:
      springframework:
        vault:
          core:
            env: DEBUG
spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres.container.local.jmpd.in:5432/payments
spring.cloud.vault:
  host: localhost
  scheme: http
  port: 8200
  fail-fast: true
  authentication: TOKEN
  token: ${VAULT_TOKEN}
  kv:
    enabled: false
  database:
    enabled: true
    role: writer
    backend: database
    username-property: spring.datasource.username
    password-property: spring.datasource.password
spring.config.import: vault://