apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: false

---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080

---
apiVersion: v1
data:
  application.yml: |
    spring:
      jpa:
        show_sql: true
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://10.6.0.180:5432/payments
    spring.cloud.vault:
      host: vault.default.svc.cluster.local
      scheme: http
      port: 8200
      fail-fast: true
      authentication: KUBERNETES
      kubernetes:
        role: payments
      kv:
        enabled: false
      database:
        enabled: true
        role: writer
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
    spring.config.import: vault://
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-10T21:09:34Z"
  name: payments-config
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments
  name: payments 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      serviceAccountName: payments 
      automountServiceAccountToken: true
      containers:
        - image: nicholasjackson/spring-vault-example:v0.0.3
          name: payments
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: payments-config